# -- zsh plugins
plugins=(git kubectl zsh-kubectl-prompt ssh-agent)
source $ZSH/oh-my-zsh.sh

export PATH=~/.local/bin:$PATH
export PATH=$PATH:/home/$username/go/bin

# -- set colors for dirs/files etc
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# -- kubectl prompt
RPROMPT='%{$FG[012]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'

alias vi=vim

# -- kubectl autocomplete
source <(kubectl completion zsh)
# -- kubectl get secrets example-secrets -o json | kpass
function kpass () { jq '.data | map_values(@base64d)' }

